version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: "@babel/core"
    versions:
    - 7.13.15
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.6
  - dependency-name: "@testing-library/react-hooks"
    versions:
    - 5.1.1
